key_size: 4096
# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint: 'https://acme-v01.api.letsencrypt.org/'
domains: ['example.com', 'example2.com']
public: '<folder-being-served-by-domain>'
letsencrypt_account_email: '<your-email-address>'
api_url: 'https://api.webfaction.com/'
username: '<webfaction-username>'
password: '<webfaction-password>'
cert_name: '<pick-a-name>'
quiet: true
