language: ruby
rvm:
- 2.2.7
branches:
  only:
   - master
   - staging
addons:
  apt:
    packages:
    - sshpass
install:
- bundle install --jobs=3 --retry=3
script:
- bin/rails test
deploy:
  #deploy to production
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/travis-webfaction-deploy.sh production
    on:
     branch: master
  #deploy to staging
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/travis-webfaction-deploy.sh staging
    on:
      branch: staging
